### ISSUE TITLE
You can't put beakers into microwaves

### ISSUE THREAD

**Issue by 77seven77seven** [Foundation-19/Foundation-19#1236]
#### Description of issue

You can't put a beaker into a microwave, therefore unable to cook spaghetti and like 65% of other foods.

#### Difference between expected and actual behavior

Put beaker into microwave: SUCCESS

reality: fail

#### Steps to reproduce

Step 1. Try and put beaker with water into microwave
Step 2. Fail

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
Not Broken, but I agree this is a weird one. 

The wiki indicates for most recipes that the microwave is needed to combine reagents. In our version this is Not true and instead the **Electric Stove** is used to combine reagents. I used this process to prepare a plate of spaghetti.

Beaker of 10 flour, 10 water, and 1 egg for 1 dough. I flattened the dough and then cut it up, then I cut up the slices into spaghetti. Instead of mixing the spaghetti and water in the microwave as the wiki suggests you can instead (and really as the only option) use the **Electric Stove**, this yielded one plate of spaghetti.
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/801e904d-8784-4184-8501-97bae68d8755)

This is true for most if not all cooking recipes that require the microwave.

**Comment by Tuulipommi** [comment]
This is not a bug, so this will be closed.
