### ISSUE TITLE
GoI rep doesn't have access to his locker

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1517]
Title

**Comment by TerryTehCoder** [comment]
This is part of a broader issue that personal lockers in general don't work. An incredibly easy fix for the GOI Rep would be restricting their personal locker to Admin_LVL1 access instead of All_Personal_Lockers which is what check tried to do in #1420 but ultimately closed. 

The reason personal lockers are spaghetti code currently is beyond me.
Check pointed to a possible issue with the "CanUseObj" topic in Topic.dm if anyone wants to investigate it. 
That's over in code\game\objects\topic.dm

**Comment by aidan-bowman** [comment]
> This is part of a broader issue that personal lockers in general don't work. An incredibly easy fix for the GOI Rep would be restricting their personal locker to Admin_LVL1 access instead of All_Personal_Lockers which is what check tried to do in #1420 but ultimately closed.
> 
> The reason personal lockers are spaghetti code currently is beyond me. Check pointed to a possible issue with the "CanUseObj" topic in Topic.dm if anyone wants to investigate it. That's over in code\game\objects\topic.dm

I did check over the files to see if it would be a quick fix. Honestly though, the ideal solution is to work out why the hell the GoI locker is a personal locker in the first place.

**Comment by TerryTehCoder** [comment]
I assume due to the fact that there aren't any "standard" secure locker templates that can be freely re-used. They're all custom themed after their respective heads. You could *Probably* use the standard secure locker but that seems pretty Jerry-rigged from a stylistic perspective.

In an ideal world this is resolved with the GOI REP getting their own secure locker sprite and just using an access locked Secure Locker.
