### ISSUE TITLE
all of the Cyborg Sprite just, don't work, except for the flying one

### ISSUE THREAD

**Issue by projectkepler-ru** [Foundation-19/Foundation-19#1769]
#### Steps to reproduce

![image](https://github.com/user-attachments/assets/da5afade-9037-494e-818a-76e5c097f5d8)
outside of the drone and flying variant. they are invisible

#### Specific information for locating

Presently all the spawnable /silicon with exception of the flying variant
are just completely invisible

#### Length of time in which bug has been known to occur

I've no fucking idea

#### Client version, Server revision & Game ID

cuL-sQJ

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by projectkepler-ru** [comment]
We really need to start having a "This can compile, run, and when I go in game it looks fine"

**Comment by checkraisefold** [comment]
please make sure to include testmerges from ooc > show server revision if your issues occur on production server with testmerges active

this was caused by a one line error when ripping out custom items in #1745 that was barely noticeable, considering it was additionally compounded by #1740 which caused it to pop up. the deployment of the testmerge has been updated on production with a fix

**Comment by projectkepler-ru** [comment]
> please make sure to include testmerges from ooc > show server revision if your issues occur on production server with testmerges active

This is entirely on you to check what PR caused the borg sprite to get changed via gitblame, not me
Please fix the issue as addressed
